### PR TITLE
add package cycle test (currently failing)

### PR DESCRIPTION
**Pull request by jakemac53**
Specifically, this is testing if transformers in two packages can consume files from each others previous phases (or even pre-existing files, neither seem to work today).

### CODE REVIEW

**Comment by jakemac53** [comment]
Sorry about the dartfmt noise, I will send a separate cl to format the package.

**Review by munificent — CHANGES_REQUESTED** [review]
The test looks great, but I'd rather not land it until it's passing. It's too easy to forget a test is skipped and end up with it being skipped forever.

**Comment by jakemac53** [comment]
Sure, it looks like skip_test doesn't print any message about it being skipped either lol

**Comment by jakemac53** [comment]
@munificent given that I won't be actually fixing this issue (for now at least), do you want me to just close this pull request or remove the `skip_` and submit so that it is a failing test?

**Comment by kevmoo** [comment]
Not planned.

**Pull request closed without merging**
